spring:
    r2dbc:
        url: "r2dbc:postgresql://localhost:5432/estapar"
        username: "postgres"
        password: "postgres"
    sql:
        init:
            mode: always

jackson:
    serialization:
        indent_output: true

client:
    garage:
        base-url: "http://localhost:3000"

management:
    endpoints:
        web:
            exposure:
                include: health,info,env

server:
    port: 3003