spring:
    r2dbc:
        url: "r2dbc:postgresql://localhost:5432/estapar"
        username: "postgres"
        password: "postgres"
    sql:
        init:
            mode: always

jackson:
    serialization:
        indent_output: true

client:
    garage:
        base-url: "http://localhost:3000"

logging:
    level:
        org.springframework.web.reactive.function.client: DEBUG

server:
    port: 3003